# Copyright 2025 ACSONE SA/NV
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

{
    "name": "Fs Folder Report Py3o",
    "summary": """Save your reports generated by Py3o into the folder associated to
    your record.""",
    "version": "18.0.1.0.0",
    "license": "AGPL-3",
    "author": "ACSONE SA/NV,Odoo Community Association (OCA)",
    "website": "https://github.com/OCA/storage",
    "depends": [
        "fs_folder_report",
        "report_py3o",
    ],
    "data": [],
    "demo": [],
    "installable": True,
    "maintainers": ["lmignon"],
}
