[project]
name = "odoo-addons-oca-storage"
version = "19.0.20260924.0"
dependencies = [
    "odoo-addon-fs_attachment==19.0.*",
    "odoo-addon-fs_attachment_environment==19.0.*",
    "odoo-addon-fs_attachment_s3==19.0.*",
    "odoo-addon-fs_attachment_s3_environment==19.0.*",
    "odoo-addon-fs_storage==19.0.*",
    "odoo-addon-fs_storage_environment==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
